version: '3.8'
services:
  redis:
    image: "redis:alpine"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "poetry run python3 listener.py"
    environment:
      - REDIS_HOST=redis
    ports:
      - '5001:5000'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - '3307:3306'
