version: '3'
services:
  redis:
    image: "redis"
    expose:
      - 6379
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
    ports:
      - '5001:5000'

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '3307:3306'

volumes:
  dbdata: